name: Build, Scan, SBOM, Sign, and Attest Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest
  REGISTRY: docker.io

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # needed for Cosign keyless
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container image (local)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (Syft)
        run: |
          syft ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -o spdx-json > sbom.spdx.json
          echo "✅ SBOM generated"
          ls -lh sbom.spdx.json

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0  # set to 1 if you want to fail on criticals

      - name: Push image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Install Cosign
        run: |
          curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign
          chmod +x /usr/local/bin/cosign

      - name: Keyless sign the image using Cosign
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --yes

      - name: Attach SBOM to image (OCI artifact in Docker Hub)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          # Attach and sign the SBOM
          cosign attach sbom --sbom sbom.spdx.json ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-sbom --yes
          echo "✅ SBOM attached and signed"

      - name: Generate provenance attestation (SLSA-style)
        run: |
          cat <<EOF > provenance.json
          {
            "builder": {
              "id": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            },
            "buildType": "https://github.com/Attestations/GitHubActions@v1",
            "invocation": {
              "parameters": {
                "ref": "${{ github.ref_name }}",
                "sha": "${{ github.sha }}"
              },
              "environment": {
                "repository": "${{ github.repository }}",
                "trigger": "${{ github.event_name }}"
              }
            },
            "materials": [
              {
                "uri": "git+https://github.com/${{ github.repository }}@${{ github.sha }}"
              }
            ]
          }
          EOF
          cat provenance.json

      - name: Attach and sign provenance attestation
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign attest \
            --predicate provenance.json \
            --type slsaprovenance \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

          echo "✅ Provenance attestation generated and attached"
